<div class="menu login">
    <?php echo $this->widget('menu_index_top');?>
    <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
        <div class="ui-dialog-content ui-widget-content">
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <div style="overflow: hidden">
                    <img alt="<?php echo $this->user->name ?>" src="upload/<?php echo $this->thumbnail($this->user->image, 'medium') ?>" />
                </div>
            <?php else: ?>
                <?php echo $this->form?>
                <div class="forgot">
                    <a href="forgot/index"><?php echo $this->translate('Forgot password') ?></a>
                </div>
				<?php if ((bool) $this->newUserToGuest) :?>
					<a href="user/form"><?php echo $this->translate('New user') ?></a>
	                <br />
				<?php endif ;?>	
            <?php endif;?>
        </div>
    </div>
    <?php echo $this->widget('menu_index_bottom');?>
</div>

<div class="box">
    <div class="main">
        <?php echo $this->widget('main_index');?>
    </div>
</div>