<div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <h3><?php echo $this->translate('course'); ?></h3>
    </div>
    <div class="courses ui-dialog-content ui-widget-content">
        <?php if (count($this->data)) :?>
            <?php foreach ($this->data as $course): ?>
                <div class="item">
                    <img alt="<?php echo $course['name'] ?>" src="upload/<?php echo $this->thumbnail($course['image'], 'small') ?>" width="40" height="40" />
                    <a href="classroom/view/id/<?php echo $course['classroom_id'] ?>"><?php echo $course['name'] ?></a>
                    <span>(<?php echo $course['classroom_name'] ?>)</span>
                    <p class="light"><?php echo substr($course['description'], 0, strpos($course['description'], '.')) ?></p>
                </div>
            <?php endforeach; ?>
            <p class="clear">
        <?php else: ?>
            <p>
               <?php echo $this->translate('You are not registred in a classroom. See'); ?>
        <?php endif;?>
               <a href="index"><?php echo $this->translate('List of available courses')?></a>
            </p>
        <?php if (count($this->finalized)) :?>
            <h3><?php echo $this->translate('Finalized')?></h3>
            <?php foreach ($this->finalized as $finalized): ?>
                <div class="item">
                    <img alt="<?php echo $finalized['name'] ?>" src="upload/<?php echo $this->thumbnail($finalized['image'], 'small') ?>" width="40" height="40" />
                    <?php echo $finalized['name'] ?>
                    <span><?php echo $this->translate($finalized['category']) ?></span>
                    <p>
                        <a href="panel/certificate/validate/uniqueId/<?php echo $finalized['unique_id']?>">
                            <img class="certificate" src="img/certificate.png" />
                            <?php echo $this->translate('Certificate')?>
                        </a>
                    </p>
                </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
</div>