<div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <h3><?php echo $this->translate('Courses');?></h3>
    </div>
    <div class="courses ui-dialog-content ui-widget-content">
        <?php if (count($this->data)):?>
            <?php foreach($this->data as $course): ?>
                <div class="item">
                    <img alt="<?php echo $course->name?>" src="upload/<?php echo $this->thumbnail($course->image, 'small')?>" width="40" height="40" />
                    <a href="course/view/id/<?php echo $course->id?>"><?php echo $course->name?></a>
                    <span><?php echo $this->translate($course->category)?></span>
                    <p class="light"><?php echo substr($course->description, 0, strpos($course->description, '.'))?></p>
                </div>
            <?php endforeach;?>
            <?php echo $this->paginationControl($this->data, null, null, $this->params); ?>
        <?php else: ?>
            <p><?php echo $this->translate('there are no records')?></p>
        <?php endif;?>
    </div>
</div>