<div id="menu">
    <?php echo $this->widget('menu_dashboard_top');?>
    <div class="box">
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
            <div class="ui-dialog-content ui-widget-content">
                <div style="overflow: hidden">
                    <img alt="<?php echo $this->user->name ?>" src="upload/<?php echo $this->thumbnail($this->user->image, 'medium') ?>" />
                </div>
            </div>
        </div>
    </div>
    <div class="button">
        <a href="user/edit" class="ui-state-default ui-corner-all" style="padding-left: 25px;">
            <span class="ui-icon ui-icon-contact"></span><?php echo $this->translate('data')?>
        </a>
        <?php if (Zend_Auth::getInstance()->getIdentity()->role == 'institution'):?>
            <a href="admin/course" class="ui-state-default ui-corner-all" style="padding-left: 25px;">
                <span class="ui-icon ui-icon-gear"></span><?php echo $this->translate('Admin')?>
            </a>
        <?php endif;?>
        <?php if (Zend_Auth::getInstance()->getIdentity()->role == 'student'):?>
            <a href="selection-process" class="ui-state-default ui-corner-all" style="padding-left: 25px;">
                <span class="ui-icon ui-icon-folder-open"></span><?php echo $this->translate('selection process')?>
            </a>
        <?php endif;?>
    </div>
    <?php echo $this->widget('menu_dashboard_bottom');?>
</div>

<div class="box">
    <div class="main">
        <?php echo $this->widget('main_dashboard');?>
    </div>
</div>