<div class="ui-dialog ui-widget ui-widget-content ui-corner-all">
    <div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
        <h3><?php echo $this->translate('timeline'); ?></h3>
    </div>
    <div class="courses ui-dialog-content ui-widget-content">
        <?php if (count($this->timeline)) :?>
            <?php foreach ($this->timeline as $timeline): ?>
                <div class="item">
                    <img alt="<?php echo $timeline['name'] ?>" src="upload/<?php echo $this->thumbnail($timeline['image'], 'small') ?>" width="40" height="40" />
                    <?php echo $timeline['name'] ?>
                    <span><?php echo $this->date($timeline['created'])?></span>
                    <p class="light"><?php echo $timeline['description']?>
                    (<a href="classroom/view/id/<?php echo $timeline['classroom_id'] ?>"><?php echo $timeline['cname']?></a>)</p>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p>
               <?php echo $this->translate('there are no records'); ?>
            </p>
        <?php endif;?>
    </div>
</div>