<?php echo $this->render('menu.phtml') ?>
<a name="start0"></a>
<div id="main">

</div>
<div id="fixed">
    <?php echo $this->widget('main_classroom');?>
</div>
<script type="text/javascript">
    $(".close").live("click", function(){
        $(this).parents('.box').remove();
        return false;
    });

    $(".fix").live("click", function(){
        $('#fixed').prepend($(this).parents('.box'));
        $(this).remove();
        return false;
    });
</script>